module App
using GenieFramework
@genietools
include("layout.jl")
include("home.jl")
include("research.jl")
include("people.jl")
include("examples/bulk.jl")
include("examples/saturation.jl")
include("examples/excess.jl")
include("examples/mixpxy.jl")
include("examples/ternary.jl")
include("examples/api_sol.jl")
include("examples/polymer.jl")
include("examples/uncertainty.jl")
include("examples/parameter_estimation.jl")
include("examples/diffusion.jl")
include("examples/cdft.jl")
include("examples/electrolytes.jl")

meta = Dict("og:title" => "Clapeyron", "og:description" => "A versatile, open-source thermodynamics toolkit for all your modelling needs.", "og:image" => "public/Clapeyron_logo.png")
layout_home = DEFAULT_LAYOUT(meta=meta,title="Clapeyron")
layout_research = DEFAULT_LAYOUT(meta=meta,title="Research")
layout_people = DEFAULT_LAYOUT(meta=meta,title="People")
layout_bulk = DEFAULT_LAYOUT(meta=meta,title="Bulk Properties")
layout_saturation = DEFAULT_LAYOUT(meta=meta,title="Saturation Properties")
layout_excess = DEFAULT_LAYOUT(meta=meta,title="Excess Properties")
layout_mixpxy = DEFAULT_LAYOUT(meta=meta,title="Binary Phase Diagrams")
layout_ternary = DEFAULT_LAYOUT(meta=meta,title="Ternary Phase Diagrams")
layout_api_sol = DEFAULT_LAYOUT(meta=meta,title="API Solubility")
layout_polymer = DEFAULT_LAYOUT(meta=meta,title="Polymer Properties")
layout_uncertainty = DEFAULT_LAYOUT(meta=meta,title="Uncertainty Propagation")
layout_parameter_estimation = DEFAULT_LAYOUT(meta=meta,title="Parameter Estimation")
layout_diffusion = DEFAULT_LAYOUT(meta=meta,title="Diffusion")
layout_cdft = DEFAULT_LAYOUT(meta=meta,title="cDFT")
layout_electrolytes = DEFAULT_LAYOUT(meta=meta,title="Electrolyte Properties")

@page("/home", "home_ui.jl", model = HOME, layout = layout_home)
@page("/research", "research_ui.jl", model = Research, layout = layout_research)
@page("/people", "people_ui.jl", model = People, layout = layout_people)
@page("/bulk_properties", "examples/bulk_ui.jl", model = BULK, layout = layout_bulk)
@page("/saturation_properties", "examples/saturation_ui.jl", model = SATURATION, layout = layout_saturation)
@page("/excess_properties", "examples/excess_ui.jl", model = EXCESS, layout = layout_excess)
@page("/binary_phase_diagrams", "examples/mixpxy_ui.jl", model = MIXPXY, layout = layout_mixpxy)
@page("/ternary_phase_diagrams", "examples/ternary_ui.jl", model = TERNARY_DIAGRAM, layout = layout_ternary)
@page("/api_solubility", "examples/api_sol_ui.jl", model = API_SOL, layout = layout_api_sol)
@page("/polymer_properties", "examples/polymer_ui.jl", model = POLYMER, layout = layout_polymer)
@page("/uncertainty_propagation", "examples/uncertainty_ui.jl", model = UNCERTAINTY, layout = layout_uncertainty)
@page("/parameter_estimation", "examples/parameter_estimation_ui.jl", model = PARAMETER_ESTIMATION, layout = layout_parameter_estimation)
@page("/diffusion", "examples/diffusion_ui.jl", model = DIFFUSION, layout = layout_diffusion)
@page("/cdft", "examples/cdft_ui.jl", model = CDFT, layout = layout_cdft)
@page("/electrolyte_properties", "examples/electrolytes_ui.jl", model = ELECTROLYTES, layout = layout_electrolytes)

route("/") do
  redirect(:get_home)
end
end